const behaviouralQuestions = [

"Tell me about yourself.",
"Walk me through your resume.",
"Why did you choose software engineering as your career?",
"Why do you want to work at this company?",
"What motivates you to work as a developer?",
"Where do you see yourself in five years?",
"Why should we hire you?",
"What is your biggest professional achievement?",
"What project are you most proud of?",
"Tell me about a challenging problem you solved.",
"Describe a time when you had to learn a new technology quickly.",
"Tell me about a time you worked under pressure.",
"Describe a time when you missed a deadline.",
"Tell me about a time you made a mistake.",
"Describe a time when you received negative feedback.",
"Tell me about a time you disagreed with a teammate.",
"Describe a time you had to convince someone to accept your idea.",
"Tell me about a time you had a conflict in a team.",
"Describe a time when teamwork helped you achieve a goal.",
"Tell me about a time you helped a teammate succeed.",
"Describe a time you took initiative on a project.",
"Tell me about a time you went beyond your responsibilities.",
"Describe a time you identified a problem before others.",
"Tell me about a time you improved a process.",
"Describe a time when you solved a problem independently.",
"Tell me about a time you handled multiple tasks simultaneously.",
"Describe a time when priorities suddenly changed.",
"Tell me about a time you had to make a difficult decision.",
"Describe a time when your idea was rejected.",
"Tell me about a time you adapted to a major change.",
"Describe a time you worked with a difficult teammate.",
"Tell me about a time you failed and what you learned.",
"Describe a time when you had to debug a complex issue.",
"Tell me about a time you optimized performance of a system.",
"Describe a time you worked on a project with unclear requirements.",
"Tell me about a time you handled tight deadlines.",
"Describe a time you had to prioritize tasks.",
"Tell me about a time you delivered results despite obstacles.",
"Describe a time when you had to step outside your comfort zone.",
"Tell me about a time you handled constructive criticism.",
"Describe a time you had to explain a technical concept to a non-technical person.",
"Tell me about a time you improved code quality.",
"Describe a time you automated a manual task.",
"Tell me about a time you handled a production issue.",
"Describe a time you improved system efficiency.",
"Tell me about a time you refactored messy code.",
"Describe a time you introduced a new idea to your team.",
"Tell me about a time your first solution did not work.",
"Describe a time when you had to research a solution.",
"Tell me about a time you handled a high-impact bug.",
"Describe a time you had to deliver a project quickly.",
"Tell me about a time you learned from a failed project.",
"Describe a time when communication solved a problem.",
"Tell me about a time miscommunication caused an issue.",
"Describe a time you clarified unclear requirements.",
"Tell me about a time you worked with cross-functional teams.",
"Describe a time you collaborated with designers or product managers.",
"Tell me about a time you mentored someone.",
"Describe a time you led a small project or initiative.",
"Tell me about a time you handled responsibility for a major task.",
"Describe a time when you had to make a quick decision.",
"Tell me about a time you handled an unexpected problem.",
"Describe a time when you improved user experience.",
"Tell me about a time you handled customer feedback.",
"Describe a time when you delivered more than expected.",
"Tell me about a time you had to persuade your team.",
"Describe a time you solved a conflict between teammates.",
"Tell me about a time you had to adapt to new tools or frameworks.",
"Describe a time you improved productivity.",
"Tell me about a time you simplified a complex problem.",
"Describe a time when you made a tough trade-off decision.",
"Tell me about a time you worked with legacy code.",
"Describe a time you fixed a critical bug.",
"Tell me about a time you improved application performance.",
"Describe a time you handled stress at work.",
"Tell me about a time you managed multiple responsibilities.",
"Describe a time when you delivered a project successfully as part of a team.",
"Tell me about a time you solved a problem creatively.",
"Describe a time you helped improve team collaboration.",
"Tell me about a time you suggested an improvement that was implemented.",
"Describe a time you worked independently on a difficult task.",
"Tell me about a time you dealt with ambiguity.",
"Describe a time you balanced speed and quality.",
"Describe a time you had to meet a strict deadline.",
"Describe a time when you motivated yourself during a difficult project.",
"Tell me about a time you handled criticism professionally.",
"Describe a time when you had to change your approach.",
"Tell me about a time you solved a customer-impacting problem.",
"Describe a time you identified a risk early.",
"Tell me about a time you handled a large workload.",
"Describe a time you worked on something outside your expertise.",
"Describe a time you showed leadership without being asked.",
"Describe a time you handled failure and recovered from it.",
"Describe a time you improved a product feature.",
"Describe a time you made an important technical decision.",
"Describe a time you solved a difficult debugging issue.",
"Describe a time when you had to compromise in a team decision.",
"Describe a time you managed conflicting priorities.",
"Describe a time you exceeded expectations on a project.",
"Describe a time you demonstrated ownership of a task or project."

]

export default behaviouralQuestions