const behaviouralQuestions = [

"Tell me about yourself.",
"Walk me through your resume.",
"Why did you choose software engineering as your career?",
"Why do you want to work at this company?",
"What motivates you to work as a developer?",
"Where do you see yourself in five years?",
"Why should we hire you?",
"What is your biggest professional achievement?",
"What project are you most proud of?",
"Tell me about a challenging problem you solved.",
"Describe a time when you had to learn a new technology quickly.",
"Tell me about a time you worked under pressure.",
"Describe a time when you missed a deadline.",
"Tell me about a time you made a mistake.",
"Describe a time when you received negative feedback.",
"Tell me about a time you disagreed with a teammate.",
"Describe a time you had to convince someone to accept your idea.",
"Tell me about a time you had a conflict in a team.",
"Describe a time when teamwork helped you achieve a goal.",
"Tell me about a time you helped a teammate succeed.",
"Describe a time you took initiative on a project.",
"Tell me about a time you went beyond your responsibilities.",
"Describe a time you identified a problem before others.",
"Tell me about a time you improved a process.",
"Describe a time when you solved a problem independently.",
"Tell me about a time you handled multiple tasks simultaneously.",
"Describe a time when priorities suddenly changed.",
"Tell me about a time you had to make a difficult decision.",
"Describe a time when your idea was rejected.",
"Tell me about a time you adapted to a major change.",
"Describe a time you worked with a difficult teammate.",
"Tell me about a time you failed and what you learned.",
"Describe a time when you had to debug a complex issue.",
"Tell me about a time you optimized performance of a system.",
"Describe a time you worked on a project with unclear requirements.",
"Tell me about a time you handled tight deadlines.",
"Describe a time you had to prioritize tasks.",
"Tell me about a time you delivered results despite obstacles.",
"Describe a time when you had to step outside your comfort zone.",
"Tell me about a time you handled constructive criticism.",
"Describe a time you had to explain a technical concept to a non-technical person.",
"Tell me about a time you improved code quality.",
"Describe a time you automated a manual task.",
"Tell me about a time you handled a production issue.",
"Describe a time you improved system efficiency.",
"Tell me about a time you refactored messy code.",
"Describe a time you introduced a new idea to your team.",
"Tell me about a time your first solution did not work.",
"Describe a time when you had to research a solution.",
"Tell me about a time you handled a high-impact bug.",
"Describe a time you had to deliver a project quickly.",
"Tell me about a time you learned from a failed project.",
"Describe a time when communication solved a problem.",
"Tell me about a time miscommunication caused an issue.",
"Describe a time you clarified unclear requirements.",
"Tell me about a time you worked with cross-functional teams.",
"Describe a time you collaborated with designers or product managers.",
"Tell me about a time you mentored someone.",
"Describe a time you led a small project or initiative.",
"Tell me about a time you handled responsibility for a major task.",
"Describe a time when you had to make a quick decision.",
"Tell me about a time you handled an unexpected problem.",
"Describe a time when you improved user experience.",
"Tell me about a time you handled customer feedback.",
"Describe a time when you delivered more than expected.",
"Tell me about a time you had to persuade your team.",
"Describe a time you solved a conflict between teammates.",
"Tell me about a time you had to adapt to new tools or frameworks.",
"Describe a time you improved productivity.",
"Tell me about a time you simplified a complex problem.",
"Describe a time when you made a tough trade-off decision.",
"Tell me about a time you worked with legacy code.",
"Describe a time you fixed a critical bug.",
"Tell me about a time you improved application performance.",
"Describe a time you handled stress at work.",
"Tell me about a time you managed multiple responsibilities.",
"Describe a time when you delivered a project successfully as part of a team.",
"Tell me about a time you solved a problem creatively.",
"Describe a time you helped improve team collaboration.",
"Tell me about a time you suggested an improvement that was implemented.",
"Describe a time you worked independently on a difficult task.",
"Tell me about a time you dealt with ambiguity.",
"Describe a time you balanced speed and quality.",
"Describe a time you had to meet a strict deadline.",
"Describe a time when you motivated yourself during a difficult project.",
"Tell me about a time you handled criticism professionally.",
"Describe a time when you had to change your approach.",
"Tell me about a time you solved a customer-impacting problem.",
"Describe a time you identified a risk early.",
"Tell me about a time you handled a large workload.",
"Describe a time you worked on something outside your expertise.",
"Describe a time you showed leadership without being asked.",
"Describe a time you handled failure and recovered from it.",
"Describe a time you improved a product feature.",
"Describe a time you made an important technical decision.",
"Describe a time you solved a difficult debugging issue.",
"Describe a time when you had to compromise in a team decision.",
"Describe a time you managed conflicting priorities.",
"Describe a time you exceeded expectations on a project.",
"Describe a time you demonstrated ownership of a task or project."

]

const dsaQuestions = [

"Implement a function to find the longest substring without repeating characters.",
"Given an array of integers, find the two numbers that add up to a target sum.",
"Implement a binary search algorithm on a sorted array.",
"Given a string, implement a function to reverse it without using built-in methods.",
"Find the maximum product of any two elements in an array.",
"Implement a function to check if a string is a palindrome.",
"Given a linked list, reverse it in-place.",
"Implement a function to find the kth largest element in an array.",
"Given an array, find all pairs that sum to a target number.",
"Implement a depth-first search (DFS) algorithm on a graph.",
"Given a binary tree, find its maximum depth.",
"Implement a function to flatten a nested array.",
"Find the longest common subsequence between two strings.",
"Given an array of integers, find the missing number.",
"Implement a function to rotate an array by k positions.",
"Given a matrix, spiral traverse it.",
"Implement a merge sort algorithm.",
"Find the number of islands in a 2D grid.",
"Given a string of parentheses, check if it's balanced.",
"Implement a quick sort algorithm.",
"Find the longest increasing subsequence in an array.",
"Given two sorted arrays, merge them into a single sorted array.",
"Implement a breadth-first search (BFS) algorithm on a graph.",
"Find all permutations of a given string.",
"Given a string, find the first non-repeating character.",
"Implement a hash table from scratch.",
"Find the minimum window substring that contains all characters from a target string.",
"Given a binary tree, check if it's a valid binary search tree.",
"Implement a function to find the median of two sorted arrays.",
"Find the longest palindromic substring in a string.",
"Given an array, find the maximum subarray sum (Kadane's algorithm).",
"Implement a trie data structure.",
"Find the edit distance between two strings (Levenshtein distance).",
"Given a graph, find the shortest path using Dijkstra's algorithm.",
"Implement a function to find the factorial of a number using recursion.",
"Given an array, find all unique triplets that sum to a target.",
"Implement a function to check if a number is prime.",
"Find the greatest common divisor (GCD) of two numbers.",
"Given a string with digits, find all possible letter combinations (phone keypad).",
"Implement a function to generate Fibonacci numbers.",
"Find the common elements between multiple arrays.",
"Given a linked list, detect if there's a cycle.",
"Implement a function to find the power of a number.",
"Find the minimum number of operations to make all array elements equal.",
"Implement a stack data structure with push, pop, and peek operations.",
"Given a matrix, rotate it 90 degrees clockwise.",
"Find all subsets of a given set (power set).",
"Implement a queue data structure with enqueue and dequeue.",
"Given a binary tree, find the level order traversal.",
"Find the number of ways to climb n stairs (climbing stairs problem).",
"Implement a function for binary tree inorder traversal.",
"Given a sorted array with a rotated point, find the minimum element.",
"Find the longest repeating character in a string.",
"Implement a function to check if two strings are anagrams.",
"Given a binary tree, serialize and deserialize it.",
"Find the median of an unsorted array.",
"Implement a function to perform topological sort on a directed graph.",
"Given a list of intervals, merge overlapping intervals.",
"Find the duplicate number in an array of n+1 integers.",
"Implement a function to find the square root of a number.",
"Given a string, remove duplicate characters while maintaining order.",
"Find the longest common prefix among multiple strings.",
"Implement a graph using an adjacency list.",
"Given an array of meeting times, find the minimum meeting rooms needed.",
"Find all unique permutations of an array with duplicates.",
"Implement a function to count the number of bits set to 1 in an integer.",
"Given a dictionary and a word, find all valid word ladder transformations.",
"Find the maximum distance between two elements with condition.",
"Implement a function for binary tree preorder traversal.",
"Given a matrix, find the path with the maximum sum.",
"Find all occurrences of a pattern in a string (KMP algorithm).",
"Implement a balanced binary search tree (AVL tree).",
"Given an array, find the first missing positive integer.",
"Find the least common multiple (LCM) of two numbers.",
"Implement a function to find x raised to the power of n efficiently.",
"Given a matrix with 0s and 1s, find the largest rectangle of 1s.",
"Find the sum of all elements in a binary tree.",
"Implement a function to convert a decimal number to binary.",
"Given a string, find the longest substring with at most k distinct characters.",
"Find all pairs in an array that form a perfect square sum."

]

export default behaviouralQuestions
export { dsaQuestions }